import { UserConfigExport } from "vite";
import react from "@vitejs/plugin-react";

export const baseConfig = {
  plugins: [react()],
  build: {
    rollupOptions: {
      external: [
        "@react-native-async-storage/async-storage",
        "@react-native-async-storage/async-storage",
        "@react-native-community/netinfo",
        "@react-native-picker/picker",
        "@reduxjs/toolkit",
        "@tanstack/react-query",
        "axios",
        "aws-amplify",
        "aws-amplify-react-native",
        "react",
        "react/jsx-runtime",
        "react-dom",
        "react-native",
        "react-native-device-info",
        "react-native-elements",
        "react-native-geocoding",
        "react-native-gesture-handler",
        "react-native-image-picker",
        "react-native-maps",
        "react-native-paper",
        "react-native-phone-call",
        "react-native-push-notification",
        "react-native-reanimated",
        "react-native-safe-area-context",
        "react-native-svg",
        "react-native-vector-icons",
        "react-native-vector-icons/MaterialCommunityIcons",
        "react-native-vector-icons/MaterialIcons",
        "react-native-webview",
        "react-redux",
        "react/jsx-runtime",
        "styled-components",
        "styled-components/native",
        "react-native-email-link",
        "react-native-pager-view",
        "react-native-actionsheet",
        "react-native-share",
        "react-native-fs",
        "@fortawesome/react-native-fontawesome",
        "@fortawesome/react-fontawesome",
        "react-native-actions-sheet",
        "@react-native-clipboard/clipboard",
      ],
      output: {
        globals: {
          react: "React",
          "react/jsx-runtime": "jsxRuntime",
          "react-native": "ReactNative",
          "react-dom": "ReactDOM",
        },
      },
    },
  },
} satisfies UserConfigExport;
